#!/bin/bash
NVIDIA_DRIVER_VERSION="${NVIDIA_DRIVER_VERSION:-535.104.12}"
CONTAINER_REGISTRY="${CONTAINER_REGISTRY:-container-registry.siomporas.com}"

helm repo add nvidia https://helm.ngc.nvidia.com/nvidia \
   && helm repo update

helm install     -n gpu-operator     --create-namespace     --set driver.repository=$CONTAINER_REGISTRY/nvidia    \
      --set driver.version=$NVIDIA_DRIVER_VERSION     gpu-operator     nvidia/gpu-operator
