#!/bin/bash

helm repo add nvidia https://helm.ngc.nvidia.com/nvidia \
   && helm repo update

helm install     -n gpu-operator     --create-namespace     --set driver.repository=$CONTAINER_REGISTRY/nvidia    \
      --set driver.version=$NVIDIA_DRIVER_VERSION     gpu-operator     nvidia/gpu-operator
